// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy-uOXrCqUEQpCE5jlZmArZBCAYi96FUw',
    appId: '1:948553954946:web:b38a9bb2da3189d765669b',
    messagingSenderId: '948553954946',
    projectId: 'moviebookingapp-75525',
    authDomain: 'moviebookingapp-75525.firebaseapp.com',
    databaseURL: 'https://moviebookingapp-75525-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'moviebookingapp-75525.appspot.com',
    measurementId: 'G-9KBRGQJ6CT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIOouVT9oIeW2NAhmzphuKgMzl7EN-wg4',
    appId: '1:948553954946:android:b1a2509a48da94dc65669b',
    messagingSenderId: '948553954946',
    projectId: 'moviebookingapp-75525',
    databaseURL: 'https://moviebookingapp-75525-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'moviebookingapp-75525.appspot.com',
  );
}
